//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Tima.rc
//
#define IDD_TIMA_DIALOG                 102
#define IDD_ATOMICCLOCK                 103
#define IDD_TRAYCLOCK                   104
#define IDD_WEATHER                     105
#define IDD_CALENDAR                    106
#define IDD_SELNTPSERVER                107
#define IDR_MAINFRAME                   128
#define IDP_SOCKETS_INIT_FAILED         129
#define IDS_LOADSKINFAILED              130
#define IDS_LOADSKININERROR             131
#define IDS_LOADSKINWITHERROR           131
#define IDS_BINDINGSKINERROR            132
#define IDS_LOADSETTINGSFAILED          133
#define IDS_LOADSETTINGSWITHERROR       134
#define IDS_SETTIMER_ERROR              135
#define IDS_AC_NEXTESTAB                200
#define IDS_AC_NEXTSTART                201
#define IDS_AC_NEXTDONE_3               202
#define IDS_AC_NEXTMANUAL               202
#define IDC_PICT_1                      1001
#define IDC_PICT_2                      1002
#define IDC_PICT_3                      1003
#define IDC_RBN_ATOMICCLOCK             1004
#define IDC_RBN_TRAYCLOCK               1005
#define IDC_RBN_WEATHER                 1006
#define IDC_RBN_REMINDER                1007
#define IDC_RBN_CALENDER                1008
#define IDC_RBN_STOPWATCH               1009
#define IDC_RBN_SETTINGS                1010
#define IDC_RBN_ABOUT                   1011
#define IDC_BUTTON1                     1012
#define IDC_BUTTON3                     1013
#define IDC_BUTTON2                     1014
#define IDC_RADIO1                      1015
#define IDC_COMBO1                      1016
#define IDC_RADIO2                      1016
#define IDC_CHECK1                      1017
#define IDC_EDIT2                       1018
#define IDC_CHECK2                      1018
#define IDC_EDIT1                       1019
#define IDC_RADIO4                      1019
#define IDC_EDIT3                       1020
#define IDC_RADIO6                      1020
#define IDC_EDT_NTPLOC                  1020
#define IDC_EDIT4                       1021
#define IDC_CHECK6                      1021
#define IDC_RADIO8                      1021
#define IDC_CHECK3                      1022
#define IDC_BUTTON4                     1022
#define IDC_EDIT5                       1023
#define IDC_BUTTON5                     1023
#define IDC_EDT_ACEVERYNUM              1023
#define IDC_SPIN1                       1024
#define IDC_BUTTON6                     1024
#define IDC_LIST1                       1025
#define IDC_EDIT6                       1026
#define IDC_CHECK7                      1026
#define IDC_RADIO3                      1026
#define IDC_EDT_ACOFFHOUR               1026
#define IDC_SPIN2                       1027
#define IDC_CHECK8                      1027
#define IDC_RADIO5                      1027
#define IDC_SPN_ACOFFHOUR               1027
#define IDC_EDIT7                       1028
#define IDC_CHECK9                      1028
#define IDC_RADIO7                      1028
#define IDC_EDT_ACOFFMIN                1028
#define IDC_SPIN3                       1029
#define IDC_CHECK4                      1029
#define IDC_SPN_ACOFFMIN                1029
#define IDC_EDIT8                       1030
#define IDC_RADIO9                      1030
#define IDC_EDT_ACOFFSEC                1030
#define IDC_SPIN4                       1031
#define IDC_SPN_ACOFFSEC                1031
#define IDC_EDIT9                       1032
#define IDC_EDT_ACOFFMS                 1032
#define IDC_SPIN5                       1033
#define IDC_SPN_ACOFFMS                 1033
#define IDC_MONTHCALENDAR1              1034
#define IDC_COMBO3                      1035
#define IDC_HTMCTL_AC1                  1036
#define IDC_HTMCTL_AC2                  1037
#define IDC_HTMCTL_AC3                  1038
#define IDC_HTMCTL_AC4                  1039
#define IDC_PICT_AC1                    1040
#define IDC_PICT_AC2                    1041
#define IDC_PICT_AC3                    1042
#define IDC_PICT_AC4                    1043
#define IDC_HTMCTL_ACLASTSTATUS         1044
#define IDC_HTMCTL_ACSYSTIME            1045
#define IDC_HTMCTL_ACSVRTIME            1046
#define IDC_HTMCTL_ACDIFFTIME           1047
#define IDC_CMB_ACOFFSIGN               1048
#define IDC_BTN_ACCHECK                 1049
#define IDC_BTN_ACADJUST                1050
#define IDC_CHK_ACSTART                 1051
#define IDC_CHK_ACESTAB                 1052
#define IDC_CHK_ACEVERY                 1053
#define IDC_SPN_ACEVERYNUM              1054
#define IDC_CMB_ACEVERYUNIT             1055
#define IDC_LST_ACSERVER                1056
#define IDC_BTN_ACSELECT                1057
#define IDC_CHK_ACOFFSET                1058
#define IDC_CHK_ACONLY                  1059
#define IDC_HTMCTL_ACNEXTSTATUS         1060
#define IDC_LST_NTPSERVER               1060
#define IDC_BTN_ACSELECT2               1061
#define IDC_BTN_ACREMOVE                1061
#define IDC_CHK_NTPCUSTOMSVR            1061
#define IDC_BTN_AUTOSEL                 1062
#define IDC_BTN_NTPAUTOSEL              1062
#define IDC_BTN_NTPADD                  1064
#define IDC_EDT_NTPSERVER               1065

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        132
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1066
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
